### ISSUE TITLE
Are Type Tags Necessary?

### ISSUE THREAD

**Issue by trans** [yaml/YAML2#1]
In my experience it is far more common to see YAML used without any type tags. Even for usecases where tags were clearly designed to be used, I always found myself forgoing them and using a simple mapping field instead, usually `type:`, but on one occasion I actually used `!:`. And I think therein lies the essence of this question. Since mappings can easily support a field to handle a type designation, and the vast majority of use cases are with mappings, then does YAML really need type tags? For example, why use:

``` yaml
  --- !point
  x: 1
  y: 2
```

When the application could just as easily handle:

``` yaml
  ---
  !: point
  x: 1
  y: 2
```

Actually, it is probably even easier to handle the later b/c in my experience YAML parsers require global type registrations to handle the former which is often not the most elegant way to handle things.

Of course, if we were just dealing with mappings, then this would be a no-brainer. But we must also consider sequences and scalars. Using tags for either of these seems to be very rare for hand edited YAML --the main usecase is likely serialized content. But if such a thing is so rare, we might consider using a mapping in those cases too:

``` yaml
  distance:
    !: meter
    value: 20.0
```

Is the above sufficient since end-users don't handle serialization formats directly nearly so often?

Personally, I'm not sure getting rid of type is the answer. I think the problem might have more to do with the syntax. For instance, I think prefixing tags detracts from the more important information, and would be more acceptable if it were suffixed, at least in the case of scalars.

``` yaml
  distance: 20.0 !meter
```

And maybe they would be less of an eye-sore if a more subtle symbol or perhaps parenthesis were used instead of an attention demanding bang!

``` yaml
  distance: 20.0 (meter)
```

In turn, I think implementors need to find better ways for programmers to handle tags. For instance:

``` yaml
--- !foo
a: 1
b: 2
```

Loading that in Ruby via `YAML.load`, will return a Hash, but there is no way to get the `foo` type. One has to register a global handler. This lack of access makes handling YAML tags a big pain sometimes.

**Comment by trans** [comment]
Occurred to me today that a scalar with a type could even be represented as a one-element mapping:

``` yaml
distance: {meter: 20.0}
```

Or

``` yaml
distance: {20.0: meter}
```

**Comment by trans** [comment]
I currently have a usecase where it looks like I am going to have to use tags in order to convey revision information, e.g.

``` yaml
--- !foo.org,2012/spec/v2
```

If I were needing this only for mappings, I would probably forgo it altogether and just use a `type` field. But I also need to do this for sequences too. Which is why I say, it looks like I will _have_ to use tags.

But it occurs to me that I might be able to use a dummy entry instead.

``` yaml
---
- '!': spec/v2
- foo
- bar
```

My specification could simply require this first throw away element to determine the sequence's type.

**Comment by tanriol** [comment]
Is this simplification really needed? A tag is a uniform (looking the same for any node type) element intended to convey information on the intended interpretation of the data.
Is it really a good idea to get rid of this concept and force everyone who needs this kind of metadata to introduce the complexity into their schema? What is the win that will be achieved by removing tags? Is it worth the resulting extra complexity both with storing this information within the document and with interoperability for these documents?

**Comment by trans** [comment]
I just recalled, sitting in the back of my subconscious this whole time, where some of these ideas actually originated and what this issue is basically driving toward: supporting types in the way (JSYNC)[http://jsync.org/] does.

**Comment by trans** [comment]
@Tanriol All good questions.

**Comment by trans** [comment]
@tanriol I agree with you, but as it stands the common implementations (almost all built on libyaml) make accessing/using tags difficult. You can't just load a YAML document and than ask for the tag of a given node. The way they generally work now, you have to already know what tags to expect, setup handlers, and then load the document. 

I am going to close this b/c I agree with you, but YAML 2.0 needs to really think about how implementations can make tags easier to use, otherwise they will continue to go unused even if they could be useful, and sometimes forced to use a JSYNC like solution instead -- something I had to do for one of my projects.

**Comment by jedwards1211** [comment]
@tanriol I think it's worth the *reduced* complexity.  JSON became popular because it was so simple.  The only reason I would use YAML instead of JSON is for the simpler syntax (excluding all the very complicated features that contradict that) and circular references.

**Comment by logrusorgru** [comment]
Hm, I see nothing useful in tags. I think it's better to get rid out of them. Type information can be non-inline. For exmaple:

```yaml
value:
  type  : ruby/object::String
  value : "Hello, YAML v2, how it's going?"
```

or

```yaml
schema:
  {container: ruby/object::Container}:
    value     :  ruby/object::String
    timestamp : ruby/object::DateTime # or how it's properly called
  {user: ruby/object::User}:
    name   : string
    age    : int
    hidden : ruby/object::Secret

data:
  container:
    value     : "some value here"
    timestamp : "4.05 PM"
  user:
    name   : Alice
    age    : 21
    hidden : "base64-encoded-secret"
```
or
```yaml
schema:
  ruby/object::Container:
    ruby/object::String:
    ruby/object::DateTime:
  ruby/object::User:
    string:
    int:
    ruby/object::Secret:

#
# the same
#
```
or
```yaml
schema: https://example.com/yaml/scheme/container-user/v1.yml

#
# the same
#
```
or
```yaml
%SCHEMA
---
# define schema here
...
---
# objects here
...
```

Anyway this YAMLs only useful for Ruby, and can't be used by other parsers. The tags/types are only useful for any-to-any decoding. But who really wants to decode something unknown? And if so, there are another approaches. I would venture that the tags was designed under pressure from the community of rubyists. Because they (the tags) look like temporary workaround or extension.

There are yaml.org/types. The types are not implemented by many YAML parsers. Because, no one need them. And because, there are another methods to determine schema of a document.
