### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by trans** [yaml/YAML2#4]
YAML already supports an internal link notation.

```
defaults: &defaults
  correspondence_address:
    street: '100 W Hubbard'
    city: 'New York'
    state: NY
development:
  <<: &defaults
  billing_address:
    street: '100 W Hubbard'
  ...
```

Could YAML support external links as well? Either or both, local files:

```
development:
  <<: &./foo.yaml/defaults
  billing_address:
    street: '100 W Hubbard'
  ...
```

And over the wire:

```
development:
  <<: &http://foo.org/foo.yaml/defaults
  billing_address:
    street: '100 W Hubbard'
  ...
```
